apiVersion: tekton.dev/v1beta1
  kind: EventListener
  metadata:
    name: hello-tekton-listener
  spec:
    triggers:
      - bindings:
          - ref: hello-goodbye-trigger-binding
        template:
          ref: hello-goodbye-trigger-template